### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by mahmoudnafifi** [hellooks/CDnet#1]
Hi, 

Thanks for sharing the code. It is a very interesting work. 

I wonder if you can share the trained models. That would help other researchers to use your network as a standard metric for color related evaluation. 

Thanks!

**Comment by hellooks** [comment]
Thank you so much for your support! I am very willing to release the trained model weights, as this would help to expand the impact of our work and gain more 🌟🌟🌟 in the community. However, since this project was sponsored by OPPO Mobile
Telecommunications Corp., I am currently seeking permission from them to do that.

**Comment by hellooks** [comment]
Hey buddy, unfortunately I received a reply saying that it's not allowed due to commercial reasons.

**Comment by mahmoudnafifi** [comment]
Thanks for your response. That makes sense.
